### ISSUE TITLE
IRON_BARS not recognized

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#17]
Spigot 1.16.1
FakeBlock 5.0.1-b2 updated from b29

No change to config.yml
Worked correctly with b29
```
lobby_city:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -2.0
    y: 6.0 
    z: 6.0 
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -3.0
    y: 4.0 
    z: 6.0 
    pitch: 0.0
    yaw: 0.0
  material-data:
    world_lobby,-3,6,6: IRON_BARS
    world_lobby,-2,4,6: IRON_BARS
    world_lobby,-2,5,6: IRON_BARS
    world_lobby,-3,4,6: IRON_BARS
    world_lobby,-2,6,6: IRON_BARS
    world_lobby,-3,5,6: IRON_BARS
```
On server startup
```
[22:58:07] [Server thread/INFO]: [FakeBlock] Enabling FakeBlock v2.0.0-SNAPSHOT-b2
[22:58:08] [TaskChainAsyncQueue Thread 2/ERROR]: TaskChain Exception on pro.husk.fakeblock.objects.MaterialWall$$Lambda$6870/0x0000000801c0c840: Could not parse data: IRON_BARS
[22:58:08] [TaskChainAsyncQueue Thread 0/ERROR]: TaskChain Exception on pro.husk.fakeblock.objects.MaterialWall$$Lambda$6870/0x0000000801c0c840: Could not parse data: IRON_BARS
[22:58:08] [TaskChainAsyncQueue Thread 1/ERROR]: TaskChain Exception on pro.husk.fakeblock.objects.MaterialWall$$Lambda$6870/0x0000000801c0c840: Could not parse data: IRON_BARS
[22:58:08] [TaskChainAsyncQueue Thread 2/ERROR]: Current Action Index was: 0
[22:58:08] [TaskChainAsyncQueue Thread 0/ERROR]: Current Action Index was: 0
[22:58:08] [TaskChainAsyncQueue Thread 1/ERROR]: Current Action Index was: 0
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]: java.lang.IllegalArgumentException: Could not parse data: IRON_BARS
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.block.data.CraftBlockData.newData(CraftBlockData.java:545)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createBlockData(CraftServer.java:1975)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createBlockData(CraftServer.java:1968)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at org.bukkit.Bukkit.createBlockData(Bukkit.java:1462)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$null$2(MaterialWall.java:100)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$loadWall$3(MaterialWall.java:88)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[22:58:08] [TaskChainAsyncQueue Thread 1/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:' at position 0: <--[HERE]
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]: java.lang.IllegalArgumentException: Could not parse data: IRON_BARS
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.block.data.CraftBlockData.newData(CraftBlockData.java:545)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createBlockData(CraftServer.java:1975)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createBlockData(CraftServer.java:1968)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at org.bukkit.Bukkit.createBlockData(Bukkit.java:1462)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$null$2(MaterialWall.java:100)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$loadWall$3(MaterialWall.java:88)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[22:58:08] [TaskChainAsyncQueue Thread 2/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:' at position 0: <--[HERE]
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]: java.lang.IllegalArgumentException: Could not parse data: IRON_BARS
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.block.data.CraftBlockData.newData(CraftBlockData.java:545)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createBlockData(CraftServer.java:1975)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at org.bukkit.craftbukkit.v1_16_R1.CraftServer.createBlockData(CraftServer.java:1968)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at org.bukkit.Bukkit.createBlockData(Bukkit.java:1462)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$null$2(MaterialWall.java:100)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$loadWall$3(MaterialWall.java:88)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[22:58:08] [TaskChainAsyncQueue Thread 0/WARN]: Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:' at position 0: <--[HERE]
```

**Comment by SlimeDog** [comment]
The configuration changed, and was not converted. Deleted config.yml, restarted server, re-created walls, and all is well.
