### ISSUE TITLE
NoClassDefFound

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#22]
Spigot 1.16.2
ProtocolLib 4.6.0-SNAPSHOT-b464
FakeBlock 2.0.1-SNAPSHOT-b11

On server start-up:
```
[07:45:23] [TaskChainAsyncQueue Thread 0/ERROR]: TaskChain Exception on pro.husk.fakeblock.objects.MaterialWall$$Lambda$6784/0x00000008018d0c40: java.lang.ExceptionInInitializerError
[07:45:23] [TaskChainAsyncQueue Thread 0/ERROR]: Current Action Index was: 0
[07:45:23] [TaskChainAsyncQueue Thread 2/ERROR]: TaskChain Exception on pro.husk.fakeblock.objects.MaterialWall$$Lambda$6784/0x00000008018d0c40: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo
[07:45:23] [TaskChainAsyncQueue Thread 1/ERROR]: TaskChain Exception on pro.husk.fakeblock.objects.MaterialWall$$Lambda$6784/0x00000008018d0c40: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]: java.lang.Exception: java.lang.ExceptionInInitializerError
[07:45:23] [TaskChainAsyncQueue Thread 2/ERROR]: Current Action Index was: 0
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.handleError(TaskChain.java:1203)
[07:45:23] [TaskChainAsyncQueue Thread 1/ERROR]: Current Action Index was: 0
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.access$600(TaskChain.java:57)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1320)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]: Caused by: java.lang.ExceptionInInitializerError
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$buildPacketList$5(MaterialWall.java:169)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.buildPacketList(MaterialWall.java:154)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$loadWall$3(MaterialWall.java:108)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         ... 7 more
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]: Caused by: java.lang.RuntimeException: Unable to find MultiBlockChangeInfo (PacketPlayOutMultiBlockChange$MultiBlockChangeInfo)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2101)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at com.comphenix.protocol.utility.MinecraftReflection.getMultiBlockChangeInfoClass(MinecraftReflection.java:1848)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         at com.comphenix.protocol.wrappers.MultiBlockChangeInfo.<clinit>(MultiBlockChangeInfo.java:38)
[07:45:23] [TaskChainAsyncQueue Thread 0/WARN]:         ... 13 more
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]: java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.handleError(TaskChain.java:1203)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.access$600(TaskChain.java:57)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1320)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$buildPacketList$5(MaterialWall.java:169)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.buildPacketList(MaterialWall.java:154)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$loadWall$3(MaterialWall.java:108)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[07:45:23] [TaskChainAsyncQueue Thread 1/WARN]:         ... 7 more
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]: java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.handleError(TaskChain.java:1203)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.access$600(TaskChain.java:57)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1320)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.lang.Thread.run(Thread.java:834)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.MultiBlockChangeInfo
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$buildPacketList$5(MaterialWall.java:169)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:928)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.buildPacketList(MaterialWall.java:154)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.objects.MaterialWall.lambda$loadWall$3(MaterialWall.java:108)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         at pro.husk.fakeblock.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[07:45:23] [TaskChainAsyncQueue Thread 2/WARN]:         ... 7 more
```

**Comment by Huskehhh** [comment]
Hey hey! It is my understanding that ProtocolLib is not completely updated to 1.16.2 yet.

**Comment by SlimeDog** [comment]
I guess that's possible, given that the last dev update was August 6. Which version of ProtocolLib is used by FB?

**Comment by Huskehhh** [comment]
> I guess that's possible, given that the last dev update was August 6. Which version of ProtocolLib is used by FB?

The ``4.5.0`` API is used, although I updated my local version to use ``4.6.0-SNAPSHOT`` API and had the same results.

**Comment by SlimeDog** [comment]
And so we'll wait. Thanks for checking it.

**Comment by SlimeDog** [comment]
16 other plugins that I test have been updated to Spigot 1.16.2, with ProtocolLib 4.6.0-b464. Just saying...

**Comment by Huskehhh** [comment]
> 16 other plugins that I test have been updated to Spigot 1.16.2, with ProtocolLib 4.6.0-b464. So my servers are up and running on Spigot 1.16.2, except for FakeBlock, which is a central component of our rank management. Just saying... :)

I understand that other plugins work, however unfortunately this is an issue with ProtocolLib not having updated to the new MultiBlockChange packet -
https://wiki.vg/Pre-release_protocol#Multi_Block_Change (1.16.2)
https://wiki.vg/Protocol#Multi_Block_Change (1.15.2)

**Comment by SlimeDog** [comment]
Thanks for the details. We'll try to be patient. :)

**Comment by Huskehhh** [comment]
Created an issue 👍 
https://github.com/dmulloy2/ProtocolLib/issues/941

**Comment by Huskehhh** [comment]
After a few days. I decided to write a fix and bypass the need for ProtocolLib with this packet while we wait for them to update.

This fix is yuck because it uses reflection, I really didn't want to have to go down this path, and will be changing back to use ProtocolLib once it becomes available.

I do recommend doing some testing before putting it on production, although I did some testing and it appears fine!

The download wont be on the GitHub actions as it needs to build against the server jar directly
http://husk.pro/dl/FakeBlock-latest-2.0.1-dev-b1.jar

Let me know if you have any issues!

**Comment by SlimeDog** [comment]
I hope it was clear that I could wait, but I appreciate your willingness.

Testing: My three fake walls are constructed of iron_bars. The bars are oriented incorrectly -- they do not attach to the solid blocks as they should do.

![Screen Shot 2020-08-20 at 10 16 20 PM](https://user-images.githubusercontent.com/17748923/90854822-d33bc100-e332-11ea-9b45-3e56c03db4b0.png)
.

**Comment by Huskehhh** [comment]
Oh absolutely not. I do apologise if my response came off that way!

husk.pro/dl/FakeBlock-latest-2.0.1-dev-b2.jar

When you get an opportunity can you please test this version. I tested locally and had no issues - however, am wondering if there's a difference in BlockData storage

If this build does not work can you please provide your config! Cheers!

**Comment by SlimeDog** [comment]
I didn't take it that way, but I try to be sensitive to cross-cultural nuance (not always successfully).

Testing dev-b2: Almost right, but note the lower right corner.
![Screen Shot 2020-08-20 at 10 47 20 PM](https://user-images.githubusercontent.com/17748923/90856713-6ecf3080-e337-11ea-8ae3-905cad9ca150.png)

In both tests, console/log reported success
```
[22:42:02] [Server thread/INFO]: [FakeBlock] Loading FakeBlock v2.0.1-SNAPSHOT
[22:43:24] [Server thread/INFO]: [FakeBlock] Enabling FakeBlock v2.0.1-SNAPSHOT
[22:43:36] [TaskChainAsyncQueue Thread 0/INFO]: [FakeBlock] Loaded wall 'lobby_city' successfully
[22:43:36] [TaskChainAsyncQueue Thread 2/INFO]: [FakeBlock] Loaded wall 'lobby_yellowdog' successfully
[22:43:36] [TaskChainAsyncQueue Thread 1/INFO]: [FakeBlock] Loaded wall 'lobby_whitedog' successfully
```
We're looking at lobby_city on the left, and lobby_whitedog on the right.
config.yml
```
inverse-permission-check: false

lobby_city:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -2.0
    y: 6.0
    z: 6.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -3.0
    y: 4.0
    z: 6.0
    pitch: 0.0
    yaw: 0.0
  material-data:
    world_lobby,-3,6,6: minecraft:iron_bars[east=true,north=false,south=false,waterlogged=false,west=true]
    world_lobby,-2,4,6: minecraft:iron_bars[east=true,north=false,south=false,waterlogged=false,west=true]
    world_lobby,-2,5,6: minecraft:iron_bars[east=true,north=false,south=false,waterlogged=false,west=true]
    world_lobby,-3,4,6: minecraft:iron_bars[east=true,north=false,south=false,waterlogged=false,west=true]
    world_lobby,-2,6,6: minecraft:iron_bars[east=true,north=false,south=false,waterlogged=false,west=true]
    world_lobby,-3,5,6: minecraft:iron_bars[east=true,north=false,south=false,waterlogged=false,west=true]
lobby_whitedog:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 6.0
    z: 3.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 4.0
    z: 2.0
    pitch: 0.0
    yaw: 0.0
  material-data:
    world_lobby,-6,4,2: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,6,3: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,5,2: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,6,2: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,4,3: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,5,3: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
lobby_yellowdog:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 6.0
    z: -2.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 4.0
    z: -3.0
    pitch: 0.0
    yaw: 0.0
  material-data:
    world_lobby,-6,6,-3: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,4,-2: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,5,-2: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,4,-3: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,6,-2: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]
    world_lobby,-6,5,-3: minecraft:iron_bars[east=false,north=true,south=true,waterlogged=false,west=false]```

**Comment by Huskehhh** [comment]
I'm weirdly unable to replicate this. If you re-create the wall does it work properly?

**Comment by Huskehhh** [comment]
I think I've hit the nail on the head now... (fingers crossed). Thanks again for all your testing and support!

New build: https://husk.pro/dl/FakeBlock-latest-2.0.1-dev-b3.jar

**Comment by SlimeDog** [comment]
Does [this](https://ci.dmulloy2.net/job/ProtocolLib/477/changes) help?

**Comment by SlimeDog** [comment]
ProtocolLib just now officially upgraded to support 1.16.2.

**Comment by Huskehhh** [comment]
Will look at adopting the changes tomorrow 😃
