### ISSUE TITLE
Unknown world in plugin enable

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#5]
Spigot 1.14.4
FakeBlock 1.6-b28

Wall defined
```
bd-rambeau-home:
  location1:
    ==: org.bukkit.Location
    world: world_blackdog
    x: 318.0
    y: 84.0
    z: -420.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_blackdog
    x: 316.0
    y: 83.0
    z: -420.0
    pitch: 0.0
    yaw: 0.0
  material: STONE
```
saved in game and worked correctly. But on server restart:
```
[22:20:21] [Server thread/ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
        at org.bukkit.Location.deserialize(Location.java:668) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:157) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:133) ~[spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at pro.husk.fakeblock.modules.LatestModule.loadWalls(LatestModule.java:16) ~[?:?]
        at pro.husk.fakeblock.FakeBlock.lambda$onEnable$0(FakeBlock.java:62) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
        at pro.husk.fakeblock.FakeBlock.onEnable(FakeBlock.java:61) [FakeBlock-1.6-b28.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar-2019-11-08-0405:git-Spigot-56f8471-56118c6]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
This is likely due to plugin enabled before Multiverse worlds were loaded.

> fakeblock reload

does not seem to help.

**Comment by Huskehhh** [comment]
An interesting bug, but with no "real" solution.

Some options: 
Add loadbefore: [FakeBlock] to multiverse's plugin.yml, 
or adding softdepend: [MultiverseCore] to FakeBlock plugin.yml

**Comment by SlimeDog** [comment]
Multiverse-Core should not require any knowledge of plugins that depend on it. I believe the correct solution is
```
load: POSTWORLD
```
in plugin.yml, but the soft depend would work as well, unless someone is using a different world manager.

**Comment by Huskehhh** [comment]
Interesting. I wonder if it'll work given it's supposedly the default
https://www.spigotmc.org/wiki/plugin-yml/
"Explicitly state when a plugin should be loaded. If not supplied will default to POSTWORLD."

Regardless, here's a build with the build order specified.

[libs.zip](https://github.com/Huskehhh/FakeBlock/files/3853894/libs.zip)

**Comment by Huskehhh** [comment]
Here's a build with the softdepend for Multiverse added... See how you go :)
[libs.zip](https://github.com/Huskehhh/FakeBlock/files/3853895/libs.zip)

**Comment by SlimeDog** [comment]
Well, that didn't solve it. :(

**Comment by SlimeDog** [comment]
I added the softdepend. That works fine.

**Comment by Huskehhh** [comment]
Cool, what a weird bug :(
Sorry I couldn't help with a more substantial solution!

**Comment by SlimeDog** [comment]
Confirmed fixed in build 30.
