### ISSUE TITLE
FieldAccessException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#6]
Spigot 1.15 (Jenkins 2509)
FakeBlock 1.7-b33

On server start-up:
```
[17:36:08] [Server thread/INFO]: [FakeBlock] Enabling FakeBlock v1.7-SNAPSHOT
[17:36:08] [Server thread/INFO]: [FakeBlock] Loading wall 'bd-rambeau-home-entry'!
[17:36:08] [Server thread/INFO]: [FakeBlock] Loaded wall 'bd-rambeau-home-entry' successfully
[17:36:08] [Server thread/INFO]: [FakeBlock] Loading wall 'bd-rambeau-home'!
[17:36:08] [Server thread/INFO]: [FakeBlock] Loaded wall 'bd-rambeau-home' successfully
[17:36:08] [Server thread/ERROR]: Error occurred while enabling FakeBlock v1.7-SNAPSHOT (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: No field with type java.util.Map exists in class EnumProtocol.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.initialize(NettyProtocolRegistry.java:60) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolRegistry.<init>(ProtocolRegistry.java:59) ~[?:?]
        at com.comphenix.protocol.injector.netty.NettyProtocolRegistry.<init>(NettyProtocolRegistry.java:39) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.initialize(PacketRegistry.java:70) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:271) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:259) ~[?:?]
        at com.comphenix.protocol.concurrency.PacketTypeSet.getPacketClass(PacketTypeSet.java:82) ~[?:?]
        at com.comphenix.protocol.concurrency.PacketTypeSet.addType(PacketTypeSet.java:35) ~[?:?]
        at com.comphenix.protocol.injector.spigot.AbstractPacketInjector.addPacketHandler(AbstractPacketInjector.java:30) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.enablePacketFilters(PacketFilterManager.java:634) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:402) ~[?:?]
        at pro.husk.fakeblock.FakeBlock.addPacketListener(FakeBlock.java:86) ~[?:?]
        at pro.husk.fakeblock.FakeBlock.onEnable(FakeBlock.java:67) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.jar-2019-12-11-1423:git-Spigot-f39a89e-beff9fb]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
This is possibly a ProtocolLib issue, but I wanted to get it on the record.

**Comment by Huskehhh** [comment]
Thanks mate! I'll keep an eye out for ProtocolLib updates D:

**Comment by SlimeDog** [comment]
FB works as expected now that ProtocolLib has been updated to support 1.15.x.
